CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(40) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS buses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_number VARCHAR(50) NOT NULL UNIQUE,
    from_city VARCHAR(100) NOT NULL,
    to_city VARCHAR(100) NOT NULL,
    departure VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS route_stops (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_id INTEGER NOT NULL REFERENCES buses(id) ON DELETE CASCADE,
    stop_order INTEGER NOT NULL,
    stop_name VARCHAR(100) NOT NULL,
    arrival_time VARCHAR(10),
    UNIQUE (bus_id, stop_order)
);

CREATE TABLE IF NOT EXISTS bus_reports (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_number VARCHAR(50),
    current_stop VARCHAR(100),
    direction VARCHAR(100),
    status VARCHAR(100),
    vote INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bus_reports_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bus_number VARCHAR(50),
    current_stop VARCHAR(100),
    direction VARCHAR(100),
    status VARCHAR(100),
    vote INTEGER DEFAULT 0,
    verified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO buses (bus_number, from_city, to_city, departure)
VALUES
    ('101', 'Bengaluru', 'Mysuru', '08:30'),
    ('205', 'Bengaluru', 'Mysuru', '09:15'),
    ('310', 'Bengaluru', 'Hubballi', '10:00')
ON CONFLICT (bus_number) DO NOTHING;

INSERT INTO route_stops (bus_id, stop_order, stop_name, arrival_time)
SELECT buses.id, stops.stop_order, stops.stop_name, stops.arrival_time
FROM (VALUES
    ('101', 1, 'Bengaluru', '08:30'),
    ('101', 2, 'Mandya', '09:35'),
    ('101', 3, 'Mysuru', '10:45'),
    ('205', 1, 'Bengaluru', '09:15'),
    ('205', 2, 'Ramanagara', '10:00'),
    ('205', 3, 'Mandya', '10:35'),
    ('205', 4, 'Mysuru', '11:30'),
    ('310', 1, 'Bengaluru', '10:00'),
    ('310', 2, 'Tumakuru', '11:10'),
    ('310', 3, 'Chitradurga', '13:00'),
    ('310', 4, 'Hubballi', '15:20')
) AS stops(bus_number, stop_order, stop_name, arrival_time)
JOIN buses ON buses.bus_number = stops.bus_number
ON CONFLICT (bus_id, stop_order) DO NOTHING;
